version: '3'

networks:
    docker_net0:
        driver: bridge


services:
    mongo:
        image: mongo:latest
        container_name: ${MONGO_CONTAINER_NAME}
        env_file:
            - .env-mongo
        ports:
            - $MONGO_PORT:27017
        environment:
           - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
           - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
           - MONGO_PASSWORD=${MONGO_PASSWORD}
        volumes:
            - ./host-data:/data/db
        restart: always
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure



